### ISSUE TITLE
Update usage information for v0.3.2

### ISSUE THREAD

**Issue by wymcg** [wymcg/matricks#97]
Update usage information in the README and on the website with the new options.
- [ ] Single-path plugin selection with `--path` changed to multi-path plugin selection with `--plugin` (#58)
- [ ] `--map-path` was renamed to `--mount`, with minor usage changes (#93)
- [ ] Several orientation and wiring options were added, including `--vertical` and the mirroring flags (#86, #87, #91)
- [ ] `--gpio`, `--dma`, and `--frequency` options were added (#83)
